yarnPath: .yarn/releases/yarn-4.5.0.cjs
nodeLinker: node-modules

enableGlobalCache: false

compressionLevel: mixed

nmMode: hardlinks-local

packageExtensions:
  'eslint-plugin-prettier@*':
    peerDependencies:
      'eslint': '*'
  '@tanstack/react-query@*':
    peerDependencies:
      'react': '*' 