//
//  AuthError.swift
//  Agora
//
//  .
//  Copyright © 2023 Palette Labs, Inc. All rights reserved.
//
//  Errors that can be generated by ASAuthorization (passkey or security key).

import AuthenticationServices

func interpretAuthError(_ error: Error) -> String {
    guard let authError = error as? ASAuthorizationError else {
        return "Unexpected auth error: \(error.localizedDescription)"
    }

    if authError.code == .canceled {
        return "User cancelled auth request"
    } else {
        // The userInfo dictionary sometimes contains useful information.
        return "Error: \((error as NSError).userInfo)"
    }
}